### ISSUE TITLE
Hi tell me which version of java and gradle you used?

### ISSUE THREAD

**Issue by vesvzial** [Sufiyan-Salman/AccountService-HyperSkill-JavaBackEndProject#1]
I can't launch your project

**Comment by Sufiyan-Salman** [comment]
Hi, please try using Java 19 along with it.

**Comment by WinterTempIQ** [comment]
Still not working(
https://photos.app.goo.gl/shu44ACr8QYzD5HM8

**Comment by WinterTempIQ** [comment]
if it's not difficult for you, you can explain how this project should be launched in general

**Comment by Sufiyan-Salman** [comment]
As It was a hyperskill project, All I did was clicked on "solve in IDE" button on the website, it redirected me in IntelliJ IDEA (mine is ultimate version) and set up everything on its own.
Now If you are doing the same, you can do the following:
-Check gradle versions in both, mine and yours.
-Set Set java version to 19.0.1, refresh the project then,
-Check the output for the errors.

**Comment by WinterTempIQ** [comment]
It worked!
And can you explain how to control this program
 I enter in the browser http://localhost:28852/api/auth/signup but nothing happens

**Comment by Sufiyan-Salman** [comment]
http://localhost:28852/api/auth/signup, as this endpoint has put mapping and browser sends get request so no response. You should test the project using POSTMAN or any similar software.
